export const PROGRAMS = [
    {
        id: 0,
        programname: "Kickboxing",
        days: "Monday", 
        time: "4:00 p.m.",
        fee: "$40.00 per month",
        place: "Rec 1",
        age: "8 and up",
        instructorname: "",
        image: "/assets/images/bootstrap-logo.png",
        active: true,
        for: "kickbox",
        description: "Bootstrap Outfitters supplies you with the gear you need at prices you can't beat."
    },
    {
        id: 1,
        programname: "Aqua Jogging",
        days: "Monday", 
        time: "9:00 a.m. to 10:00 a.m.",
        fee: "Free",
        place: "pool",
        age: "",
        instructorname: "",
        image: "/assets/images/bootstrap-logo.png",
        active: true,
        for: "aqua",
        description: "An informal exercise group at the pool. Water exercise improves circulation, lowers blood pressure, and increases range of motion without the stress of gravity."   
    },
    {
        id: 2,
        programname: "Orbix Fitness",
        days: "Monday",
        time: "8:00 p.m. to 9:00 p.m.",
        fee: "$5.00 per class",
        place: "Rec 2",
        age: "",
        instructorname: "",
        image: "/assets/images/bootstrap-logo.png",
        active: true,
        for: "orbix",
        description: "A Tahitian style fitness class that will get you moving. Don’t forget to bring your water bottle and a pareo if you have one."  
    },
    {
        id: 3,
        programname: "Yoga Plain & Simple",
        days: "Saturday",
        time: "8:00 a.m. to 9:00 a.m.",
        fee: "$5.00 per class or $20.00 per month",
        place: "Rec 1",
        age: "",
        instructorname: "Harry Winfield",
        image: "/assets/images/bootstrap-logo.png",
        active: false,
        description: "Bootstrap Outfitters supplies you with the gear you need at prices you"   
    },
]