export const PROGRAMS = [
    {
        id: 0,
        programname: "Kickboxing",
        days: "Mondays & Wednesdays", 
        time: "4:00 p.m.",
        fee: "$40.00 per month",
        place: "Rec 1",
        age: "8 and up",
        instructorname: "to be determined",
        image: "/assets/images/kickboxing.jpg",
        alt: "Kickboxing",
        active: true,
        for: "kickbox",
        description: "Bootstrap Outfitters supplies you with the gear you need at prices you can't beat."
    },
    {
        id: 1,
        programname: "Aqua Jogging",
        days: "Mondays, Wednesdays, Fridays", 
        time: "9:00 a.m. to 10:00 a.m.",
        fee: "Free",
        place: "pool",
        age: "",
        instructorname: "to be determined",
        image: "/assets/images/pool.jpg",
        alt: "Aqua Jogging",
        active: true,
        for: "aqua",
        description: "An informal exercise group at the pool. Water exercise improves circulation, lowers blood pressure, and increases range of motion without the stress of gravity."   
    },
    {
        id: 2,
        programname: "Orbix Fitness",
        days: "Mondays",
        time: "8:00 p.m. to 9:00 p.m.",
        fee: "$5.00 per class",
        place: "Rec 2",
        age: "",
        instructorname: "to be determined",
        image: "/assets/images/orbix.jpg",
        alt: "Orbix Fitness",
        active: true,
        for: "orbix",
        description: "A Tahitian style fitness class that will get you moving. Don’t forget to bring your water bottle and a pareo if you have one."  
    },
    {
        id: 3,
        programname: "Yoga Plain & Simple",
        days: "Saturdays",
        time: "8:00 a.m. to 9:00 a.m.",
        fee: "$5.00 per class or $20.00 per month",
        place: "Rec 1",
        age: "",
        instructorname: "Harry Winfield",
        image: "/assets/images/kapolei_chair_yoga.jpg",
        alt: "Yoga Plain & Simple",
        active: true,
        for: "yoga",
        description: "Bootstrap Outfitters supplies you with the gear you need at prices you"   
    },
    {
        id: 4,
        programname: "Zumba & Pound Fitness Classes",
        days: "Mondays and most Wednesdays",
        time: "7:00 p.m. - 8:30 p.m.",
        fee: "$5.00 per class",
        place: "Rec 1",
        age: "",
        instructorname: "Anela Jackson",
        image: "/assets/images/zumba.png",
        alt: "Zumba & Pound Fitness Classes",
        active: true,
        for: "zumba",
        description: "BooDance your way to fitness with Zumba, then drum up a healthier you with Pound fitness. Pound uses lightly weighted exercise drumsticks to engage the whole body. Tone, sculpt and cardio the fun way."   
    },  
    {
        id: 5,
        programname: "Club Scouts",
        days: "",
        time: "",
        fee: "to be determined",
        place: "to be determined",
        age: "Grades 1 - 5",
        instructorname: "to be determined",
        image: "/assets/images/kapolei_boy_scouts.jpg",
        alt: "Club Scouts",
        active: true,
        for: "clubScouts",
        description: "Children in grades 1 - 5 enjoy activities which focus on developing character, improving fitness, teaching practical skills and community service. See their Facebook page @cubscoutpack126kapolei for more information."   
    },
    {
        id: 6,
        programname: "Girl Scouts",
        days: "2nd & 4th Tuesdays",
        time: "5:30 p.m.",
        fee: "to be determined",
        place: "Rec. 1",
        age: "Grades K - 12",
        instructorname: "to be determined",
        image: "/assets/images/girl_scouts_hawaii_2.jpg",
        alt: "Girl Scouts",
        active: true,
        for: "girlScouts",
        description: "Girls in grades K - 12 engage in skill-based badges, make friends, explore leadership opportunities, work collaboratively and serve their community. For more information contact gshwestside@gmail.com or visit us at https://www.gshawaii.org/."   
    },
    {
        id: 7,
        programname: "Karate",
        days: "Tuesdays & Thursdays",
        time: "6:30 p.m.",
        fee: "$40.00 per month",
        place: "Rec. 1",
        age: "",
        instructorname: "to be determined",
        alt: "Karate",
        image: "/assets/images/karate.jpg",
        active: true,
        for: "karate",
        description: "Combines physical and mental benefits such as self-discipline, respect, concentration and courtesy"   
    },
    {
        id: 8,
        programname: "Tropic Lightening Taekwondo",
        days: "Tuesdays & Thursdays",
        time: "5:00 p.m. - 7:00 p.m",
        fee: " est. $90.00 per month (varies)",
        place: "Rec. 2",
        age: "",
        instructorname: "to be determined",
        image: "/assets/images/kapolei_taekwondo.jpg",
        alt: "Tropic Lightening Taekwondo",
        active: true,
        for: "taekwondo",
        description: "Martial arts skills with an emphasis on confidence, respect, discipline and character development. Free 2-week introductory trial."   
    },
    {
        id: 9,
        programname: "Keiki Steps",
        days: "Mondays - Thursdays",
        time: "8:30 a.m. - 11:30 a.m.",
        fee: "Free",
        place: "Rec. 1",
        age: "birth to 5, with a parent/adult",
        instructorname: "to be determined",
        image: "/assets/images/kapolei_keiki_steps.jpg",
        alt: "Keiki Steps",
        active: true,
        for: "keikiSteps",
        description: "This free parent participation preschool prepares children for school through a variety of developmentally and culturally appropriate activities. Register by calling 620-9043 or email info@inpeace.org."   
    },
    {
        id: 10,
        programname: "Junior Swim Team",
        days: "Mondays, Wednesdays, Fridays",
        time: "4:00 p.m. - 5:30 p.m.",
        fee: "$50.00 per month",
        place: "Rec. 1",
        age: "6 - 18",
        instructorname: "to be determined",
        image: "/assets/images/kapolei_pool_junior_swim_2.jpg",
        alt: "Junior Swim",
        active: true,
        for: "jrSwim",
        description: "Stroke refinement, conditioning, discipline and exercise. Pre-test minimum: 100 yards continuous swimming with 3 out of 4 competitive strokes at a level 5/6 standard. Call the recreation office for more information 674-4444, dept. 2."   
    },
    {
        id: 11,
        programname: "KPOK (Kapali i ka Poli ‘Ohu o na Pali Ka’ala) Cultural Hui",
        days: "Mondays & Wednesdays",
        time: "5:00 p.m. - 8:00 p.m",
        fee: "$25.00 per month (Workshops TBD)",
        place: "Rec. 2",
        age: "6 - 18",
        instructorname: "to be determined",
        image: "/assets/images/hulaclass.jpg",
        alt: "KPOK Cultural Hui",
        active: true,
        for: "kpok",
        description: "Learn about the Hawaiian culture through language, song, dance and Polynesian cultural exchange experiences."   
    },
    {
        id: 11,
        programname: "Hip Hop",
        days: "Tuesdays & Thursdays",
        time: "4:00 p.m. – 6:30 p.m.",
        fee: "$45.00 per month",
        place: "Rec. 1",
        age: "6 - 18",
        instructorname: "to be determined",
        image: "/assets/images/hiphop2.jpg",
        alt: "Hip Hop",
        active: true,
        for: "hipHop",
        description: "A fun hip hop class that teaches youth about Hawaii’s hip hop culture"   
    }
]